# Site settings
title: Jenna McClelland
email: jenna.mcclelland@mail.utoronto.ca
description: > # this means to ignore newlines until "baseurl:"
  Jenna McClelland's collection of work and thoughts
baseurl: ""
url: "http://jennamcclelland.com"
tumblr: "http://commun1stdaughter.tumblr.com/"

# Build settings
markdown: kramdown
