# Site settings
title: Jenna McClelland
email: jennalindseymcclelland@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jenna McClelland's collection of art
baseurl: ""
url: "http://jennamcclelland.com"
tumblr: "http://commun1stdaughter.tumblr.com/"

# Build settings
markdown: kramdown
